---
title: "p8105_hw6_dw3093"
author: "Katherine Wang"
output: github_document
---

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(modelr)
library(mgcv)
library(broom)
set.seed(1)
```

#QUESTION 2
```{r}
homicide_raw <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv",
                          na = c("Unknown", "NA", ""))
```
```{r}
homicide <- homicide_raw %>%
  mutate(
    city_state = str_c(city, state, sep = ", "), 
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) %>%
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black")
  ) %>%
  drop_na(victim_age, victim_sex, victim_race, solved) 
```

```{r}
baltimore_raw <- homicide |> filter(city_state == "Baltimore, MD")
model <- glm(solved ~ victim_age + victim_sex + victim_race,
                       data = baltimore_raw, family = "binomial")
baltimore_results <- broom::tidy(model, conf.int = TRUE) %>%
  filter(term == "victim_sexMale") %>%
  mutate(
    OR = exp(estimate),     
    CI_lower = exp(conf.low), 
    CI_upper = exp(conf.high)
  ) %>%
  select(OR, CI_lower, CI_upper) %>%
  knitr::kable(digits = 3)
baltimore_results
```

```{r}
city_results <- homicide %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(
    model = map(data, ~glm(solved ~ victim_age + victim_sex + victim_race, 
                           data = ., family = "binomial")),
    results = map(model, ~broom::tidy(., conf.int = TRUE) %>%
                    filter(term == "victim_sexMale") %>%
                    mutate(
                      OR = exp(estimate), 
                      CI_lower = exp(conf.low), 
                      CI_upper = exp(conf.high))
                  )
  ) %>%
  unnest(results) %>%
  select(city_state, OR, CI_lower, CI_upper)
print(city_results %>% knitr::kable(digits = 3))
```
```{r}
city_results %>%
  mutate(city_state = reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point(color = "pink") +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper), width = .2) + 
  coord_flip() +
  labs(
    title = "Adjusted Odds Ratios for Solving Homicides by City",
    x = "City, State",
    y = "Odds Ratio (Male vs. Female Victims)"
  ) +
  theme(
    axis.text = element_text(size = 6),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

